log:
  level: debug
  format: console
kafka:
  url: localhost:9092
  env: dev # set it to dev if you would like to disable protoregistry
rpcs:
  ethereum:
    full:
      - your infura websocket endpoint here
