package compound

import (
	"github.com/nakji-network/connector/examples/compound/cBAT"
	"github.com/nakji-network/connector/examples/compound/cCOMP"
	"github.com/nakji-network/connector/examples/compound/cDAI"
	"github.com/nakji-network/connector/examples/compound/cETH"
	"github.com/nakji-network/connector/examples/compound/cLINK"
	"github.com/nakji-network/connector/examples/compound/cREP"
	"github.com/nakji-network/connector/examples/compound/cSAI"
	"github.com/nakji-network/connector/examples/compound/cTUSD"
	"github.com/nakji-network/connector/examples/compound/cUNI"
	"github.com/nakji-network/connector/examples/compound/cUSDC"
	"github.com/nakji-network/connector/examples/compound/cUSDT"
	"github.com/nakji-network/connector/examples/compound/cWBTC"
	"github.com/nakji-network/connector/examples/compound/cWBTC2"
	"github.com/nakji-network/connector/examples/compound/cZRX"

	"google.golang.org/protobuf/proto"
)

var protos = []proto.Message{
	&cBAT.Mint{},
	&cBAT.Redeem{},
	&cBAT.Borrow{},
	&cBAT.RepayBorrow{},
	&cBAT.LiquidateBorrow{},
	&cCOMP.Mint{},
	&cCOMP.Redeem{},
	&cCOMP.Borrow{},
	&cCOMP.RepayBorrow{},
	&cCOMP.LiquidateBorrow{},
	&cDAI.Mint{},
	&cDAI.Redeem{},
	&cDAI.Borrow{},
	&cDAI.RepayBorrow{},
	&cDAI.LiquidateBorrow{},
	&cETH.Mint{},
	&cETH.Redeem{},
	&cETH.Borrow{},
	&cETH.RepayBorrow{},
	&cETH.LiquidateBorrow{},
	&cLINK.Mint{},
	&cLINK.Redeem{},
	&cLINK.Borrow{},
	&cLINK.RepayBorrow{},
	&cLINK.LiquidateBorrow{},
	&cREP.Mint{},
	&cREP.Redeem{},
	&cREP.Borrow{},
	&cREP.RepayBorrow{},
	&cREP.LiquidateBorrow{},
	&cSAI.Mint{},
	&cSAI.Redeem{},
	&cSAI.Borrow{},
	&cSAI.RepayBorrow{},
	&cSAI.LiquidateBorrow{},
	&cTUSD.Mint{},
	&cTUSD.Redeem{},
	&cTUSD.Borrow{},
	&cTUSD.RepayBorrow{},
	&cTUSD.LiquidateBorrow{},
	&cUNI.Mint{},
	&cUNI.Redeem{},
	&cUNI.Borrow{},
	&cUNI.RepayBorrow{},
	&cUNI.LiquidateBorrow{},
	&cUSDC.Mint{},
	&cUSDC.Redeem{},
	&cUSDC.Borrow{},
	&cUSDC.RepayBorrow{},
	&cUSDC.LiquidateBorrow{},
	&cUSDT.Mint{},
	&cUSDT.Redeem{},
	&cUSDT.Borrow{},
	&cUSDT.RepayBorrow{},
	&cUSDT.LiquidateBorrow{},
	&cWBTC.Mint{},
	&cWBTC.Redeem{},
	&cWBTC.Borrow{},
	&cWBTC.RepayBorrow{},
	&cWBTC.LiquidateBorrow{},
	&cWBTC2.Mint{},
	&cWBTC2.Redeem{},
	&cWBTC2.Borrow{},
	&cWBTC2.RepayBorrow{},
	&cWBTC2.LiquidateBorrow{},
	&cZRX.Mint{},
	&cZRX.Redeem{},
	&cZRX.Borrow{},
	&cZRX.RepayBorrow{},
	&cZRX.LiquidateBorrow{},
}
