// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: kafkautils/onlytime.proto

package kafkautils

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// This is for unmarshaling all proto messages to get timestamp. Requires all other proto definitions to have Timestamp in index 1
type OnlyTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *OnlyTime) Reset() {
	*x = OnlyTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkautils_onlytime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlyTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlyTime) ProtoMessage() {}

func (x *OnlyTime) ProtoReflect() protoreflect.Message {
	mi := &file_kafkautils_onlytime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlyTime.ProtoReflect.Descriptor instead.
func (*OnlyTime) Descriptor() ([]byte, []int) {
	return file_kafkautils_onlytime_proto_rawDescGZIP(), []int{0}
}

func (x *OnlyTime) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_kafkautils_onlytime_proto protoreflect.FileDescriptor

var file_kafkautils_onlytime_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x6f, 0x6e, 0x6c,
	0x79, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x61, 0x66,
	0x6b, 0x61, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x08, 0x4f, 0x6e, 0x6c, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x19,
	0x5a, 0x17, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6b,
	0x61, 0x66, 0x6b, 0x61, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kafkautils_onlytime_proto_rawDescOnce sync.Once
	file_kafkautils_onlytime_proto_rawDescData = file_kafkautils_onlytime_proto_rawDesc
)

func file_kafkautils_onlytime_proto_rawDescGZIP() []byte {
	file_kafkautils_onlytime_proto_rawDescOnce.Do(func() {
		file_kafkautils_onlytime_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafkautils_onlytime_proto_rawDescData)
	})
	return file_kafkautils_onlytime_proto_rawDescData
}

var file_kafkautils_onlytime_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafkautils_onlytime_proto_goTypes = []interface{}{
	(*OnlyTime)(nil),              // 0: kafkautils.OnlyTime
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kafkautils_onlytime_proto_depIdxs = []int32{
	1, // 0: kafkautils.OnlyTime.Timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kafkautils_onlytime_proto_init() }
func file_kafkautils_onlytime_proto_init() {
	if File_kafkautils_onlytime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafkautils_onlytime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlyTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafkautils_onlytime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafkautils_onlytime_proto_goTypes,
		DependencyIndexes: file_kafkautils_onlytime_proto_depIdxs,
		MessageInfos:      file_kafkautils_onlytime_proto_msgTypes,
	}.Build()
	File_kafkautils_onlytime_proto = out.File
	file_kafkautils_onlytime_proto_rawDesc = nil
	file_kafkautils_onlytime_proto_goTypes = nil
	file_kafkautils_onlytime_proto_depIdxs = nil
}
