# https://github.com/stellar/go/blob/abd5fb704c80fc5635f181bb11396ac640b7f40a/.github/workflows/go.yml
name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:

  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        # For pull requests, build and test the PR head not a merge of the PR with the destination.
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.go }}
    #- run: ./gomod.sh
    - run: go mod tidy
    - run: go mod verify
    #- run: ./gofmt.sh
    #- run: ./gogenerate.sh
    #- run: ./govet.sh
    - run: go vet -all -composites=false -unreachable=false -tests=false ./...
    #- run: ./staticcheck.sh

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        # For pull requests, build and test the PR head not a merge of the PR with the destination.
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.go }}
    - run: go build ./...

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
        pg: [9.6.5, 10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        # For pull requests, build and test the PR head not a merge of the PR with the destination.
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        # We need to full history for git-restore-mtime to know what modification dates to use.
        # Otherwise, the Go test cache will fail (due to the modification time of fixtures changing).
        fetch-depth: '0'
    - uses: ./.github/actions/setup-go
      with:
        go-version: ${{ matrix.go }}
    - run: go test -race -cover ./...
